version: '3.5'

services:
  backend:
      image: bakkis
      environment:
        PORT: 8000 
      ports:
        - '8000:8000'
  frontend:
      image: frontti
      environment:
        PORT: 5000
        API_URL: 'http://localhost:8000'
      ports:
        - '5000:5000'